### ISSUE TITLE
My Submissions - Zoom feature

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#167]
### While status is Received or Under Review:
- Click Zoom to orient the map to the extent of both the (highlighted) BLM point _**and**_ the entered coordinates for the monument record. 
- A point should appear at the location of the entered/submitted coordinates. Different color and/or shape than PLSS points to distinguish it.
    - Include an option to clear this point from the map.
    - If cleared, the user can click Zoom to see it again and the map orients as described above.
- If user clicks Zoom on a different submission record, the submitted point for the previously-selected record disappears.

#### Exception
- If no coordinates were entered (e.g. existing sheet), then just zoom to the BLM point.

### When status is Published
- Click Zoom to zoom to the PLSS point. A point for the submitted coordinates will not display. Only after the fabric has been updated and published for the app will the point actually appear in the new location of the submitted coordinates.

**Comment by steveoh** [comment]
I chose to implement the most basic feature first since I think the requirements overlap with #176 and I wanted to let that sort itself out before adding all of that.

The map centers on the location with no graphics shown to differentiate their point vs our point. This is the case for the reference points as well. The sorting works for the reference points now. Since there is no issue tracking that i figured i'd notify you here so you can test it.

I added a db trigger for all submissions that adds a location to the record from the blm point if no coordinates are specified with the submission. This way every submission has a location and can be zoomed to.

**Comment by nathankota** [comment]
Validated:
> The map centers on the location with no graphics shown to differentiate their point vs our point. This is the case for the reference points as well. The sorting works for the reference points now. Since there is no issue tracking that i figured i'd notify you here so you can test it.

**Comment by nathankota** [comment]
Based on the info below, I am going to close this and we can add any necessary tasks after #176.

> I chose to implement the most basic feature first since I think the requirements overlap with #176 and I wanted to let that sort itself out before adding all of that.

> I added a db trigger for all submissions that adds a location to the record from the blm point if no coordinates are specified with the submission. This way every submission has a location and can be zoomed to.
