### ISSUE TITLE
Feet to meters conversion

### ISSUE THREAD

**Issue by steveoh** [agrc/PLSS#21]
I have noticed that when grid coordinates are entered as US Survey feet in the the online data submittal, the system automatically converts the coordinate from US Survey Feet to Meters when generating the Monument Record Sheet.  I checked the converted coordinates, and it appears that the conversion factor used by the system is slightly off what it should be.  I've attached the sheet previews that resulted first from entering the coordinates below first as US Survey Feet, and then as Meters using the conversion factor 1 m = 39.37/12 usft.  The resulting grid coordinates computed from the online system are different from my calculations by 0.085m in the Northing, and 0.016m in the Easting.

```Grid Coordinates (US Survey Foot)
Northing                 10435569.502
Easting                  1646720.855
Elevation                7091.206
Latitude (DMS)           N38°17'43.44768"
Longitude (DMS)          W111°28'40.92344"
Ellipsoid Height         7032.649
```

I suspect that the program uses a truncated value of the conversion ratio 39.37/12, but that it wasn't carried out to a sufficient number of decimal places to accurately convert values in the range of 10 million feet.  Please advise.

**Comment by steveoh** [comment]
The conversion units are in this [extension class](https://github.com/agrc/PLSS/blob/master/PLSS/Extensions/ConversionExtensions.cs)

The expected conversion value is
`39.37/12 = 3.280833333`

The method on line 12 is using which matches the expected conversion value
`return feet / 3.280833333f;`

There are a few other places to look into for possible precision reduction. 

1. The conversion between float and double. I will test this with actual values.
1. The writing to the PDF
1. The database field type `float(8)` @seanfernandez/@mheagin is that enough precision for the 10 million feet thing from above?

**Comment by steveoh** [comment]
Switching from the static `3.280833333` to `39.37/12` gets the numbers a bit closer to what Rodney is expecting.

**Comment by seanfernandez** [comment]
Yes, we only want 3 decimal places displayed on the sheets, but need to go
out to probably closer to 10 or 11 decimal places for the conversion
calculation.
We want to be within a centimeter of the geographic coordinate after the
conversion from US survey foot to meters. The decimeter error shown by the
surveyor is too much.
Thanks!

Sent from my iPhone

On Apr 30, 2018, at 11:00 AM, steveoh <notifications@github.com> wrote:

Switching from the static 3.280833333 to 39.37/12 gets the numbers a bit
closer to what Rodney is expecting.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/agrc/PLSS/issues/21#issuecomment-385461528>, or mute
the thread
